- hendrix_today_app/lib/Widgets/EventList.dart
- hendrix_today_app/pubspec.yaml
This will address issue #10 and add in a share icon at the bottom of the event AlertDialog. When pressed, the icon will open the native share API for the phone, bringing in the title and description of the event.
> Adding in the Share button for Events.

- hendrix_today_app/lib/Widgets/EventList.dart
Things are bigger, and scrollable when lots of text.
> Editing Event Dialogs

- hendrix_today_app/lib/Widgets/event_list.dart
Added an invisible buffer at the end of `EventList`s so that they can scroll past the floating navigation buttons
Closes #19
> 19 Can't scroll to last event

- hendrix_today_app/lib/widgets/event_calendar.dart
- hendrix_today_app/lib/widgets/screen_container.dart
- hendrix_today_app/pubspec.yaml
There is only the Month option for the calendar now, closes #30. Took a while to see that the selection option would disappear by only giving it one option.
I made the scroll-back date go back two years instead of one, partially addressing #3, but not completely. There is no way to make it infinite scrolling. So we might have to search by earliest date, and just record that in appState when the events are updated from Firebase?
Also partially addresses #52. Now calendar events will show up for the current day when loaded.
> Fixing the calendar issues

- hendrix_today_app/lib/objects/app_state.dart
- hendrix_today_app/lib/objects/event.dart
- hendrix_today_app/lib/screens/home_screen.dart
- hendrix_today_app/lib/widgets/event_calendar.dart
- hendrix_today_app/lib/widgets/event_dialog.dart
- hendrix_today_app/lib/widgets/screen_container.dart
- hendrix_today_app/pubspec.lock
`Event` objects now store much more information; items will only appear on the home page if the current date is within the item's posting date range; and the dropdown filter on the app bar now works on the pages above which it appears (the home and calendar pages).
I know we discussed during our 2023/06/21 meeting that the home page should probably only show announcements, so that may be a future issue. Also a known issue in this PR that will need to be logged after merging is that updating the dropdown filter on the app bar doesn't update the contents of the event list beneath the calendar. 
Closes #4, closes #37, closes #57
> Added more Event details, home page is time-sensitive, fixed app bar event filter

- hendrix_today_app/lib/screens/resource_screen.dart
- hendrix_today_app/lib/widgets/screen_container.dart
Technically not an embedded web browser - there is an option for that (`LaunchMode.inAppWebView`), but its behavior on Android is to open the website on top of the app with no way to leave but to swipe back or press the device's back button, which is the initial behavior that raised this issue. I assume its behavior on iOS is desirable, but I feel like modifying link behavior based on platform just to avoid writing a custom embedded-browser page for Android isn't the right thing to do.
Closes #28
> Caf menu and submission form open in external web browser

- hendrix_today_app/lib/objects/app_state.dart
- hendrix_today_app/lib/objects/event.dart
- hendrix_today_app/lib/screens/home_screen.dart
Events are now sorted by date everywhere, since the sorting is done in `AppState`. The soonest events will appear first (the same as in the Hendrix Today emails).
Closes #50
> The default event sort is by date

- hendrix_today_app/lib/widgets/event_calendar.dart
The calendar's functional range begins at the earlier of today and the earliest event and ends at the later of today and the latest event (the calendar package requires that the focused date lie within the functional range).
Closes #3
> Fixed the calendar scrolling range

- hendrix_today_app/lib/screens/calendar_screen.dart
- hendrix_today_app/lib/widgets/event_calendar.dart
Cleaned up the `EventCalendar` widget by removing unnecessary code and moving `EventList`-related code to the `CalendarScreen`.
Closes #72
> Refactored the calendar screen code

- lib/widgets/event_dialog.dart
This adds a Flexible widget to wrap the SingleChildScrollView, without it, there is no scrolling. Closes #114
> Added Flexible to make the description scroll

- lib/widgets/event_card.dart
- lib/widgets/event_dialog.dart
- pubspec.lock
Event Titles shown on their card and dialog pop-up have now been limited through use of maxLines and overflow modifiers of the Text data type. This also includes Updated Dependencies.
This is intended to be a last resort fix to the title issue. If this is accepted as a genuine fix, there will also be the related issue with having to display the full title somewhere for the user to see if it is severely long enough. Politely asking the managers of Hendrix Today to put a message that tells submissions to write concise titles would also help to reduce the number of occasions this issue may rear its head.
> Basic Event Title Limiter Added

- lib/widgets/event_card.dart
- lib/widgets/event_dialog.dart
The limiter on Event Titles has been improved to allow button functionality. That is, when a user wants to see the full length of an event title that has exceed the maximum line limit, they will be able to press the new TextButton disguised as ellipsis to view it. This button only appears on events with such limit breaking titles and will immediately disappear after the title has been extended to its full length.
This also resulted in the Event Dialog Stateless Widget becoming a Stateful Widget so that the title changes could be seen in real time.
> Title Limiter Improvements

- lib/widgets/event_dialog.dart
An Icon now appears on each Event Dialog allowing the User to directly email the Hendrix Today team to report errors on the specific event.
> Added Report Event Icon and Functionality

- lib/widgets/event_dialog.dart
The Event Dialog pop-up has been limited to a certain width and height depending on the screen size of a device.
> Limiting Size of Event Dialog

- lib/widgets/event_card.dart
During feedback, it was found that the previous icon for unread messages was unclear. After looking at icons for similar apps, I found that they use a simple dot to convey unread messages/emails/events etc. Therefore, I have changed it to a simple dot too. Sometimes, simple is better, and I hope that this is the case for these darn icons.
> Read/Unread Icon Changed

- lib/widgets/event_card.dart
Utilizing the extra whitespace on the Event Card, deadlines now appear next to the date of an event. The original idea appeared too discreet and too mysterious for a user to understand. So, I found a solution that directly solves this while also being unique to each event.
> Deadline Appears on Event Card

- lib/screens/home_screen.dart
- lib/widgets/floating_nav_buttons.dart
Due to the similarities between the Search and Home page, it has been decided that we should try to just have one instead of both. As such, I've taken a scorched earth approach and simply put all of Search Page's code onto the Home page, while deleting the original Search Page along with all references to it. The original Home Page code has also  been overwritten by the Search Page code. There is no longer a Filter List, if the Filter List was to be kept, let me know!
> Search on Home

- lib/screens/home_screen.dart
The search bar now has an X button to delete a user's search query. It is only active when there is something in the text field, otherwise, it will be a simple search icon.
> Button to Clear Search Bar

- lib/objects/theme_provider.dart
- lib/widgets/root_app.dart
- lib/widgets/toggle_bar.dart
- Themes would previously only let you have Dark mode enabled on the launching of the app.
- This is now changed to persist on relaunching the app
- The initial value is be dependent on the system theme
Closes #175
> Got Theme Persistence Working

- lib/screens/resource_screen.dart
- lib/widgets/resource_button.dart
- lib/widgets/toggle_bar.dart
The Resource Screen Buttons besides the Dark/Light Mode Toggle have been made to adjust to the size of the text within instead of being a large fixed size within a SizedBox. This may not be a complete solution as the padding size may differ between devices of different resolution.
> Resource Screen Buttons now adjusted
