DiscoTrayStudios/hendrix-today

hendrix_today_app/android/build.gradle, hendrix_today_app/lib/Screens/SearchScreen.dart, hendrix_today_app/lib/Screens/TestScreen.dart, hendrix_today_app/lib/Widgets/EventList.dart, hendrix_today_app/lib/Widgets/RootApp.dart, hendrix_today_app/lib/Widgets/ScreenContainer.dart, hendrix_today_app/macos/Flutter/GeneratedPluginRegistrant.swift, hendrix_today_app/windows/flutter/generated_plugin_registrant.cc, hendrix_today_app/windows/flutter/generated_plugins.cmake
App runs on android. Closes #22
=> App runs on android

hendrix_today_app/lib/Widgets/event_list.dart
=> 25 Change to more commonly recognized share icon on event dialogs

hendrix_today_app/lib/Widgets/event_card.dart, hendrix_today_app/lib/Widgets/event_dialog.dart
I weighted the fonts, reorganized the dialog title to include the date and time, made just the content scrollable to keep the title always visible, and added an orange bar to the left of the card, and the title section of the dialog. No rounded corners, everything is a rectangle.
Closes #47
=> Adding unique style to cards and dialog boxes

hendrix_today_app/lib/Objects/Event.dart, hendrix_today_app/lib/Objects/app_state.dart, hendrix_today_app/lib/Screens/search_screen.dart, hendrix_today_app/lib/Widgets/event_calendar.dart
Used an `EventList` to display calendar events correctly and cleaned up `widgets/event_calendar.dart`.
Closes #20
=> Calendar event cards are now the same as everywhere else

.gitignore, hendrix_today_app/ios/Podfile.lock, hendrix_today_app/ios/Runner.xcodeproj/project.pbxproj, hendrix_today_app/ios/Runner.xcworkspace/contents.xcworkspacedata, hendrix_today_app/ios/Runner/Info.plist, hendrix_today_app/lib/Widgets/event_dialog.dart
Added the GoogleService-Info.plist in the correct way.
Closes #62
=> App now runs in the iOS emulator

hendrix_today_app/lib/Widgets/event_dialog.dart
I got the x in the upper left with a stack, and some unfortunate hardcoded numbers in a Positioned (I don't know why -16 worked). I also needed to shrink the title box since the x could overlap in some circumstances. I also made it orange. I'm starting to get too many oranges, it is probably time for the ColorScheme and Theme work.
closes #60
=> Moving the x to the upper right.

hendrix_today_app/lib/screens/search_screen.dart
=> Search results page no longer starts empty

hendrix_today_app/lib/widgets/event_dialog.dart, hendrix_today_app/lib/widgets/rich_description.dart, hendrix_today_app/pubspec.lock, hendrix_today_app/pubspec.yaml
Uses a DOM parser from the html package (officially published by tools.dart.dev) to search over the description and convert anchor tags with `href` links into hyperlink text.
Closes #51
=> Added HTML-formatted hyperlinks to descriptions

hendrix_today_app/android/build.gradle, hendrix_today_app/lib/objects/app_state.dart, hendrix_today_app/lib/objects/event.dart, hendrix_today_app/lib/objects/event_type.dart, hendrix_today_app/lib/screens/home_screen.dart, hendrix_today_app/lib/widgets/event_calendar.dart, hendrix_today_app/lib/widgets/screen_container.dart
- The "Lost & Found" type has been removed
- The dropdown filter has been rearranged to be in the same order as the Hendrix Today newsletters
- An "All" filter type has been added
- The calendar no longer shows announcements, and the type filter has been removed from this page
Closes #75
=> Updated the event type filter

hendrix_today_app/lib/objects/theme_data.dart, hendrix_today_app/lib/screens/calendar_screen.dart, hendrix_today_app/lib/screens/home_screen.dart, hendrix_today_app/lib/screens/resource_screen.dart, hendrix_today_app/lib/screens/search_screen.dart, hendrix_today_app/lib/widgets/event_card.dart, hendrix_today_app/lib/widgets/event_dialog.dart, hendrix_today_app/lib/widgets/floating_nav_buttons.dart, hendrix_today_app/lib/widgets/resource_button.dart, hendrix_today_app/lib/widgets/rich_description.dart, hendrix_today_app/lib/widgets/root_app.dart
Moved the app's color and text style definitions to a single file, `lib/objects/theme_data.dart`
Closes #79
=> Centralized the color scheme and text theme

hendrix_today_app/lib/objects/event_type.dart, hendrix_today_app/lib/objects/theme_data.dart, hendrix_today_app/lib/screens/calendar_screen.dart, hendrix_today_app/lib/screens/home_screen.dart, hendrix_today_app/lib/screens/resource_screen.dart, hendrix_today_app/lib/screens/search_screen.dart, hendrix_today_app/lib/widgets/event_card.dart, hendrix_today_app/lib/widgets/event_dialog.dart, hendrix_today_app/lib/widgets/floating_nav_buttons.dart, hendrix_today_app/lib/widgets/resource_button.dart, hendrix_today_app/lib/widgets/rich_description.dart, hendrix_today_app/lib/widgets/root_app.dart, hendrix_today_app/pubspec.lock
Added a dark theme and a button in the navigation bar to toggle the theme. This button can be moved later if necessary; toggling the theme is simply a call to `RootApp.of(context).toggleThemeMode()`.
Closes #46
=> Added a dark mode

lib/widgets/event_calendar.dart
Colors now use the primary, secondary, tertiary colors from our theme. The circles are now squares, and the chevrons are visible. Closes #88
=> Customized Calendar colors and shapes

lib/widgets/event_calendar.dart
=> Reload calendar page event list when calendar month changes

lib/screens/calendar_screen.dart, lib/screens/search_screen.dart, lib/widgets/event_calendar.dart
=> Fixed Inconsistent Event Visibility

lib/widgets/event_card.dart
Previous ! Icon was bad. It was barely noticeable, its changed to something better and more eye-catching.
=> Changing Unread Icon

lib/widgets/event_dialog.dart
Share formatting is now `text(link)` Closes #134
=> Fixed Share formatting

lib/screens/home_screen.dart
=> Removed ReadAll button from Home page

lib/widgets/event_calendar.dart, pubspec.lock
- Calendar no longer allows user to go to months where there are no active events. Closes #131
=> Fixed Calendar Bug

lib/screens/resource_screen.dart
added +1 to PSAFE number. It should now work but I am not sure with the pixel phone.
=> fixed PSAFE number

ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, ios/Runner/AppDelegate.swift, ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json, ios/Runner/GoogleService-Info.plist, ios/Runner/Info.plist, ios/Runner/Runner.entitlements, lib/main.dart, lib/widgets/event_dialog.dart, macos/Flutter/GeneratedPluginRegistrant.swift, pubspec.lock, pubspec.yaml
Notifications Now fully working on both Apple and Android devices.
This allows us to setup daily notifications and push event change notifications as needed in firebase.
Closes #6
Closes #142
=> Notifications

lib/objects/theme_data.dart, lib/widgets/event_list.dart, lib/widgets/toggle_bar.dart
Events are now separated by labelled days and spaces decluttering the Home Screen and making it clearer what days what events are.
=> Events have spaces between days

lib/screens/home_screen.dart
The searchbar will either be a textfield that the user can type in or a SizedBox.shrink() depending on a boolean value. This effectively makes it so that the searchbar will appear or disappear. The boolean value is controlled by an IconButton that is a search icon when the searchbar is not displayed and is an upwards arrow when it is displayed. This upwards arrow communicates to the user that it should be pressed to hide the searchbar again. 
closes #211
=> The Search Bar Now Acts as a Dropdown
